experiment_id: FIXED_FINE_R2R_VAL_UNSEEN_FULL
base_config: run_r2r/iter_train.yaml
checkpoint: data/logs/checkpoints/release_r2r/ckpt.iter12000.pth
pretrained_language: data/pretrained/ETP/mlm.sap_r2r/ckpts/model_step_82500.pt
split: val_unseen
episodes: 1839
gpu: [0, 1]
num_environments: 8
rl_topo_enabled: false
back_algo: control
action_abstraction: fine

seed: 100
